#!/bin/sh

# =============================================================================
# Post-install hook file for configuring dotcloud server

echo "Writing the local settings file..."
echo "  - Setting the path to the Shareabouts config"
echo "  - Setting the dataset access location and key"

cat >> src/config/local_settings.py <<EOF

import json
import os.path

with open('/home/dotcloud/environment.json') as f:
    env = json.load(f)

SHAREABOUTS = {
    'DATASET_KEY': env.get('SHAREABOUTS_DATASET_KEY', 'SHAREABOUTS_DATASET_KEY-not-set-in-dotcloud-environment!!!'),
    'DATASET_ROOT': env.get('SHAREABOUTS_DATASET_ROOT', 'SHAREABOUTS_DATASET_ROOT-not-set-in-dotcloud-environment!!!'),

    'CONTEXT': {
        'analytics_key': env.get('SHAREABOUTS_ANALYTICS_KEY', 'SHAREABOUTS_ANALYTICS_KEY-not-set-in-dotcloud-environment!!!'),
        'feedback_key': env.get('SHAREABOUTS_FEEDBACK_KEY', 'SHAREABOUTS_FEEDBACK_KEY-not-set-in-dotcloud-environment!!!'),
    },

    'CONFIG': os.path.dirname(__file__)
}

STATIC_ROOT = '/home/dotcloud/current/static/'

# Debug is False by default, true if set in the environment.
DEBUG = (env.get('DEBUG', 'False') in ['true', 'True'])
TEMPLATE_DEBUG = DEBUG
ALLOWED_HOSTS = [env.get('DOTCLOUD_WWW_HTTP_HOST')] + env.get('ALLOWED_HOSTS', '').split(',')

EOF

echo "Setting up static file service..."
src/manage.py collectstatic --noinput

echo "Configuring nginx to serve static files..."
cat >> nginx.conf <<EOF
location /static/ { root /home/dotcloud/current ; }
EOF

echo "Compiling translations..."
cd src/surveyor
../manage.py compilemessages
cd ../..
