# Settings for the app
app:
  # HTML Title
  title: CB3 Survey
  # Header name
  name: CB3 Survey
  # Meta description that will show up in Google search results
  meta_description: _(Surveyor is a tool for collecting business local information)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  options:
    center:
      lat: 40.7267
      lng: -73.9808
    zoom: 14
    minZoom: 10
    maxZoom: 17

    # Disable interaction?
    dragging: true
    zoomControl: false
    touchZoom: true
    scrollWheelZoom: false
    doubleClickZoom: true
    boxZoom: false
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

survey:
  items:

# General Business Information
# ----------------------------

    - prompt: _(Business Name)
      type: text
      name: business_name

    - prompt: _(Type of Business)
      name: business_type
      type: select
      options:
        - label: _(Vacant)
          value: vacant
        - label: _(Retail)
          value: retail
        - label: _(Bar)
          value: bar
        - label: _(Restaurant)
          value: restaurant
        - label: _(Service Business)
          value: service
        - label: _(Bank)
          value: bank
        - label: _(Grocery Store)
          value: grocery
        - label: _(Deli/Bodega)
          value: deli
        - label: _(Newspaper Stand)
          value: newspapers
        - label: _(Religious)
          value: religious
        - label: _(Cultural)
          value: cultural
        - label: _(Residential)
          value: residential
        - label: _(Other)
          value: other

    - prompt: _(What is sold?)
      name: retail_type
      condition:
        - field: business_type
          value: retail
      type: select
      options:
        - label: _(Clothing)
          value: clothing
        - label: _(Medical/Alternative Medicine)
          value: medical
        - label: _(Arts & Design)
          value: arts_design
        - label: _(Gifts)
          value: gifts
        - label: _(Jewelry)
          value: jewelry
        - label: _(Other)
          value: other

    - prompt: _(Other retail...)
      name: retail_type_other
      condition:
        - field: retail_type
          value: other
      type: text

    - prompt: _(Type of Food)
      name: food_type
      type: text
      condition:
        - field: business_type
          value: restaurant

    - prompt: _(Type of service offered)
      name: service_type
      condition:
        - field: business_type
          value: service
      type: text

    - prompt: _(Wheelchair accessible?)
      name: wheelchair_accessible
      type: switch

    - prompt: _(Hours of Operation)
      type: textarea
      name: hours

# Merchant Information
# --------------------

    - type: fieldset
      label: _(Merchant Information)
      name: merchant_information
      items:
        - prompt: _(Contact Name)
          type: text
          name: contact_name

        - prompt: _(Contact Phone Number)
          type: tel
          name: phone_number
          attrs:
            - key: placeholder
              value: _((___) ___-____)

        - prompt: _(Contact Fax Number)
          type: tel
          name: fax_number
          attrs:
            - key: placeholder
              value: _((___) ___-____ )

        - prompt: _(Email Address)
          type: email
          name: email_address

        - prompt: _(Web Address)
          type: url
          name: web_address
          attrs:
            - key: placeholder
              value: 'http://'

        - prompt: _(Number of Employees)
          type: number
          name: num_of_employee

        - prompt: _(Opening Date)
          type: date
          name: opening_date

        - prompt: _(Owner Place of Residence)
          type: textarea
          name: owner_residence

        - label: _(Owner identifies as...)
          type: fieldset
          name: owner_identity
          items:
            - type: toggle
              label: _(Caucasian)
              name: owner_is_caucasian
            - type: toggle
              label: _(African American)
              name: owner_is_african_american
            - type: toggle
              label: _(Hispanic)
              name: owner_is_hispanic
            - type: toggle
              label: _(Asian)
              name: owner_is_asian
            - type: toggle
              label: _(Veteran)
              name: owner_is_veteran
            - type: toggle
              label: _(Female)
              name: owner_is_female

    - type: fieldset
      name: listing_issues
      items:
        - prompt: _(Are there any issues with this listing?)
          type: switch
          name: problems

        - prompt: ""
          type: textarea
          name: problem_description
          attrs:
            - key: placeholder
              value: _(Note issues with the listing here.)
          condition:
            - field: problems
              value: checked
